-- 코드를 입력하세요
SELECT PRODUCT_CODE, SUM(SALES_AMOUNT) * PRODUCT.PRICE AS SALES
FROM PRODUCT
    INNER JOIN OFFLINE_SALE AS SALE
    ON PRODUCT.PRODUCT_ID = SALE.PRODUCT_ID
GROUP BY SALE.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE